-- MySQL Script generated by MySQL Workbench
-- Sat Nov 21 18:02:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema api-notebook
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema api-notebook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `api-notebook` DEFAULT CHARACTER SET utf8 ;
USE `api-notebook` ;

-- -----------------------------------------------------
-- Table `api-notebook`.`notebook`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api-notebook`.`notebook` (
  `notebook_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` CHAR(16) CHARACTER SET 'utf8mb4' NOT NULL,
  `title` VARCHAR(256) CHARACTER SET 'utf8mb4' NOT NULL,
  `order` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`notebook_id`),
  UNIQUE INDEX `account_id_title_unique` USING BTREE (`account_id`, `title`) VISIBLE,
  UNIQUE INDEX `account_id_order_unique` (`account_id` ASC, `order` ASC) VISIBLE,
  FULLTEXT INDEX `title` (`title`) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
PACK_KEYS = Default;


-- -----------------------------------------------------
-- Table `api-notebook`.`page`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api-notebook`.`page` (
  `page_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `notebook_id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(256) CHARACTER SET 'utf8mb4' NOT NULL,
  `order` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`page_id`),
  UNIQUE INDEX `notebook_id_order_unique` (`notebook_id` ASC, `order` ASC) VISIBLE,
  FULLTEXT INDEX `title` (`title`) VISIBLE,
  INDEX `notebook_id_idx` (`notebook_id` ASC) VISIBLE,
  CONSTRAINT `fk_notebook_id`
    FOREIGN KEY (`notebook_id`)
    REFERENCES `api-notebook`.`notebook` (`notebook_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `api-notebook`.`section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api-notebook`.`section` (
  `section_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `page_id` INT UNSIGNED NULL,
  `content` TEXT CHARACTER SET 'utf8mb4' NOT NULL,
  `is_trashed` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`section_id`),
  INDEX `page_id_idx` (`page_id` ASC) VISIBLE,
  FULLTEXT INDEX `content` (`content`) VISIBLE,
  CONSTRAINT `fk_page_id`
    FOREIGN KEY (`page_id`)
    REFERENCES `api-notebook`.`page` (`page_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `api-notebook`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api-notebook`.`tag` (
  `tag_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) CHARACTER SET 'utf8mb4' NOT NULL,
  `account_id` CHAR(16) CHARACTER SET 'utf8mb4' NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`tag_id`),
  FULLTEXT INDEX `name` (`name`) VISIBLE,
  UNIQUE INDEX `name_account_id_unique` (`account_id` ASC, `name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `api-notebook`.`section_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api-notebook`.`section_tag` (
  `section_id` INT UNSIGNED NOT NULL,
  `tag_id` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`section_id`, `tag_id`),
  INDEX `fk_tag_id_idx` (`tag_id` ASC) VISIBLE,
  CONSTRAINT `fk_section_id`
    FOREIGN KEY (`section_id`)
    REFERENCES `api-notebook`.`section` (`section_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tag_id`
    FOREIGN KEY (`tag_id`)
    REFERENCES `api-notebook`.`tag` (`tag_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
