/*
 * This file is generated by jOOQ.
 */
package habanero.extensions.database.tables.records;


import habanero.extensions.database.tables.Notebook;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotebookRecord extends UpdatableRecordImpl<NotebookRecord> implements Record6<UInteger, String, String, UInteger, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -1185188727;

    /**
     * Setter for <code>api-notebook.notebook.notebook_id</code>.
     */
    public NotebookRecord setNotebookId(UInteger value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api-notebook.notebook.notebook_id</code>.
     */
    public UInteger getNotebookId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>api-notebook.notebook.account_id</code>.
     */
    public NotebookRecord setAccountId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api-notebook.notebook.account_id</code>.
     */
    public String getAccountId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api-notebook.notebook.title</code>.
     */
    public NotebookRecord setTitle(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api-notebook.notebook.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>api-notebook.notebook.order</code>.
     */
    public NotebookRecord setOrder(UInteger value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api-notebook.notebook.order</code>.
     */
    public UInteger getOrder() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>api-notebook.notebook.created_at</code>.
     */
    public NotebookRecord setCreatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>api-notebook.notebook.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>api-notebook.notebook.updated_at</code>.
     */
    public NotebookRecord setUpdatedAt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>api-notebook.notebook.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UInteger, String, String, UInteger, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UInteger, String, String, UInteger, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return Notebook.NOTEBOOK.NOTEBOOK_ID;
    }

    @Override
    public Field<String> field2() {
        return Notebook.NOTEBOOK.ACCOUNT_ID;
    }

    @Override
    public Field<String> field3() {
        return Notebook.NOTEBOOK.TITLE;
    }

    @Override
    public Field<UInteger> field4() {
        return Notebook.NOTEBOOK.ORDER;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Notebook.NOTEBOOK.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Notebook.NOTEBOOK.UPDATED_AT;
    }

    @Override
    public UInteger component1() {
        return getNotebookId();
    }

    @Override
    public String component2() {
        return getAccountId();
    }

    @Override
    public String component3() {
        return getTitle();
    }

    @Override
    public UInteger component4() {
        return getOrder();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component6() {
        return getUpdatedAt();
    }

    @Override
    public UInteger value1() {
        return getNotebookId();
    }

    @Override
    public String value2() {
        return getAccountId();
    }

    @Override
    public String value3() {
        return getTitle();
    }

    @Override
    public UInteger value4() {
        return getOrder();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value6() {
        return getUpdatedAt();
    }

    @Override
    public NotebookRecord value1(UInteger value) {
        setNotebookId(value);
        return this;
    }

    @Override
    public NotebookRecord value2(String value) {
        setAccountId(value);
        return this;
    }

    @Override
    public NotebookRecord value3(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public NotebookRecord value4(UInteger value) {
        setOrder(value);
        return this;
    }

    @Override
    public NotebookRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public NotebookRecord value6(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public NotebookRecord values(UInteger value1, String value2, String value3, UInteger value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotebookRecord
     */
    public NotebookRecord() {
        super(Notebook.NOTEBOOK);
    }

    /**
     * Create a detached, initialised NotebookRecord
     */
    public NotebookRecord(UInteger notebookId, String accountId, String title, UInteger order, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Notebook.NOTEBOOK);

        set(0, notebookId);
        set(1, accountId);
        set(2, title);
        set(3, order);
        set(4, createdAt);
        set(5, updatedAt);
    }
}
