/*
 * This file is generated by jOOQ.
 */
package habanero.extensions.database.tables.records;


import habanero.extensions.database.tables.Page;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PageRecord extends UpdatableRecordImpl<PageRecord> implements Record6<UInteger, UInteger, String, UInteger, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1168722893;

    /**
     * Setter for <code>api-notebook.page.page_id</code>.
     */
    public PageRecord setPageId(UInteger value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api-notebook.page.page_id</code>.
     */
    public UInteger getPageId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>api-notebook.page.notebook_id</code>.
     */
    public PageRecord setNotebookId(UInteger value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api-notebook.page.notebook_id</code>.
     */
    public UInteger getNotebookId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>api-notebook.page.title</code>.
     */
    public PageRecord setTitle(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api-notebook.page.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>api-notebook.page.order</code>.
     */
    public PageRecord setOrder(UInteger value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api-notebook.page.order</code>.
     */
    public UInteger getOrder() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>api-notebook.page.created_at</code>.
     */
    public PageRecord setCreatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>api-notebook.page.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>api-notebook.page.updated_at</code>.
     */
    public PageRecord setUpdatedAt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>api-notebook.page.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UInteger, UInteger, String, UInteger, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UInteger, UInteger, String, UInteger, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return Page.PAGE.PAGE_ID;
    }

    @Override
    public Field<UInteger> field2() {
        return Page.PAGE.NOTEBOOK_ID;
    }

    @Override
    public Field<String> field3() {
        return Page.PAGE.TITLE;
    }

    @Override
    public Field<UInteger> field4() {
        return Page.PAGE.ORDER;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Page.PAGE.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Page.PAGE.UPDATED_AT;
    }

    @Override
    public UInteger component1() {
        return getPageId();
    }

    @Override
    public UInteger component2() {
        return getNotebookId();
    }

    @Override
    public String component3() {
        return getTitle();
    }

    @Override
    public UInteger component4() {
        return getOrder();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component6() {
        return getUpdatedAt();
    }

    @Override
    public UInteger value1() {
        return getPageId();
    }

    @Override
    public UInteger value2() {
        return getNotebookId();
    }

    @Override
    public String value3() {
        return getTitle();
    }

    @Override
    public UInteger value4() {
        return getOrder();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value6() {
        return getUpdatedAt();
    }

    @Override
    public PageRecord value1(UInteger value) {
        setPageId(value);
        return this;
    }

    @Override
    public PageRecord value2(UInteger value) {
        setNotebookId(value);
        return this;
    }

    @Override
    public PageRecord value3(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public PageRecord value4(UInteger value) {
        setOrder(value);
        return this;
    }

    @Override
    public PageRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public PageRecord value6(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public PageRecord values(UInteger value1, UInteger value2, String value3, UInteger value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PageRecord
     */
    public PageRecord() {
        super(Page.PAGE);
    }

    /**
     * Create a detached, initialised PageRecord
     */
    public PageRecord(UInteger pageId, UInteger notebookId, String title, UInteger order, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Page.PAGE);

        set(0, pageId);
        set(1, notebookId);
        set(2, title);
        set(3, order);
        set(4, createdAt);
        set(5, updatedAt);
    }
}
