/*
 * This file is generated by jOOQ.
 */
package habanero.extensions.database.tables.records;


import habanero.extensions.database.tables.SectionTag;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SectionTagRecord extends UpdatableRecordImpl<SectionTagRecord> implements Record4<UInteger, UInteger, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 90558795;

    /**
     * Setter for <code>api-notebook.section_tag.section_id</code>.
     */
    public SectionTagRecord setSectionId(UInteger value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api-notebook.section_tag.section_id</code>.
     */
    public UInteger getSectionId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>api-notebook.section_tag.tag_id</code>.
     */
    public SectionTagRecord setTagId(UInteger value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api-notebook.section_tag.tag_id</code>.
     */
    public UInteger getTagId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>api-notebook.section_tag.created_at</code>.
     */
    public SectionTagRecord setCreatedAt(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api-notebook.section_tag.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>api-notebook.section_tag.updated_at</code>.
     */
    public SectionTagRecord setUpdatedAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api-notebook.section_tag.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UInteger, UInteger> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<UInteger, UInteger, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<UInteger, UInteger, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return SectionTag.SECTION_TAG.SECTION_ID;
    }

    @Override
    public Field<UInteger> field2() {
        return SectionTag.SECTION_TAG.TAG_ID;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return SectionTag.SECTION_TAG.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return SectionTag.SECTION_TAG.UPDATED_AT;
    }

    @Override
    public UInteger component1() {
        return getSectionId();
    }

    @Override
    public UInteger component2() {
        return getTagId();
    }

    @Override
    public LocalDateTime component3() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component4() {
        return getUpdatedAt();
    }

    @Override
    public UInteger value1() {
        return getSectionId();
    }

    @Override
    public UInteger value2() {
        return getTagId();
    }

    @Override
    public LocalDateTime value3() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value4() {
        return getUpdatedAt();
    }

    @Override
    public SectionTagRecord value1(UInteger value) {
        setSectionId(value);
        return this;
    }

    @Override
    public SectionTagRecord value2(UInteger value) {
        setTagId(value);
        return this;
    }

    @Override
    public SectionTagRecord value3(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public SectionTagRecord value4(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public SectionTagRecord values(UInteger value1, UInteger value2, LocalDateTime value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SectionTagRecord
     */
    public SectionTagRecord() {
        super(SectionTag.SECTION_TAG);
    }

    /**
     * Create a detached, initialised SectionTagRecord
     */
    public SectionTagRecord(UInteger sectionId, UInteger tagId, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(SectionTag.SECTION_TAG);

        set(0, sectionId);
        set(1, tagId);
        set(2, createdAt);
        set(3, updatedAt);
    }
}
