/*
 * This file is generated by jOOQ.
 */
package habanero.extensions.database.tables.records;


import habanero.extensions.database.tables.Section;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SectionRecord extends UpdatableRecordImpl<SectionRecord> implements Record6<UInteger, UInteger, String, Byte, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -1812434494;

    /**
     * Setter for <code>api-notebook.section.section_id</code>.
     */
    public SectionRecord setSectionId(UInteger value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api-notebook.section.section_id</code>.
     */
    public UInteger getSectionId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>api-notebook.section.page_id</code>.
     */
    public SectionRecord setPageId(UInteger value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api-notebook.section.page_id</code>.
     */
    public UInteger getPageId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>api-notebook.section.content</code>.
     */
    public SectionRecord setContent(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api-notebook.section.content</code>.
     */
    public String getContent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>api-notebook.section.is_trashed</code>.
     */
    public SectionRecord setIsTrashed(Byte value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api-notebook.section.is_trashed</code>.
     */
    public Byte getIsTrashed() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>api-notebook.section.created_at</code>.
     */
    public SectionRecord setCreatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>api-notebook.section.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>api-notebook.section.updated_at</code>.
     */
    public SectionRecord setUpdatedAt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>api-notebook.section.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UInteger, UInteger, String, Byte, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UInteger, UInteger, String, Byte, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return Section.SECTION.SECTION_ID;
    }

    @Override
    public Field<UInteger> field2() {
        return Section.SECTION.PAGE_ID;
    }

    @Override
    public Field<String> field3() {
        return Section.SECTION.CONTENT;
    }

    @Override
    public Field<Byte> field4() {
        return Section.SECTION.IS_TRASHED;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Section.SECTION.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Section.SECTION.UPDATED_AT;
    }

    @Override
    public UInteger component1() {
        return getSectionId();
    }

    @Override
    public UInteger component2() {
        return getPageId();
    }

    @Override
    public String component3() {
        return getContent();
    }

    @Override
    public Byte component4() {
        return getIsTrashed();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component6() {
        return getUpdatedAt();
    }

    @Override
    public UInteger value1() {
        return getSectionId();
    }

    @Override
    public UInteger value2() {
        return getPageId();
    }

    @Override
    public String value3() {
        return getContent();
    }

    @Override
    public Byte value4() {
        return getIsTrashed();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value6() {
        return getUpdatedAt();
    }

    @Override
    public SectionRecord value1(UInteger value) {
        setSectionId(value);
        return this;
    }

    @Override
    public SectionRecord value2(UInteger value) {
        setPageId(value);
        return this;
    }

    @Override
    public SectionRecord value3(String value) {
        setContent(value);
        return this;
    }

    @Override
    public SectionRecord value4(Byte value) {
        setIsTrashed(value);
        return this;
    }

    @Override
    public SectionRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public SectionRecord value6(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public SectionRecord values(UInteger value1, UInteger value2, String value3, Byte value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SectionRecord
     */
    public SectionRecord() {
        super(Section.SECTION);
    }

    /**
     * Create a detached, initialised SectionRecord
     */
    public SectionRecord(UInteger sectionId, UInteger pageId, String content, Byte isTrashed, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Section.SECTION);

        set(0, sectionId);
        set(1, pageId);
        set(2, content);
        set(3, isTrashed);
        set(4, createdAt);
        set(5, updatedAt);
    }
}
