/*
 * This file is generated by jOOQ.
 */
package habanero.extensions.database.tables.records;


import habanero.extensions.database.tables.Tag;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagRecord extends UpdatableRecordImpl<TagRecord> implements Record5<UInteger, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -1384982394;

    /**
     * Setter for <code>api-notebook.tag.tag_id</code>.
     */
    public TagRecord setTagId(UInteger value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api-notebook.tag.tag_id</code>.
     */
    public UInteger getTagId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>api-notebook.tag.name</code>.
     */
    public TagRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api-notebook.tag.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api-notebook.tag.account_id</code>.
     */
    public TagRecord setAccountId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api-notebook.tag.account_id</code>.
     */
    public String getAccountId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>api-notebook.tag.created_at</code>.
     */
    public TagRecord setCreatedAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api-notebook.tag.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>api-notebook.tag.updated_at</code>.
     */
    public TagRecord setUpdatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>api-notebook.tag.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UInteger, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UInteger, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return Tag.TAG.TAG_ID;
    }

    @Override
    public Field<String> field2() {
        return Tag.TAG.NAME;
    }

    @Override
    public Field<String> field3() {
        return Tag.TAG.ACCOUNT_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Tag.TAG.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Tag.TAG.UPDATED_AT;
    }

    @Override
    public UInteger component1() {
        return getTagId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getAccountId();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component5() {
        return getUpdatedAt();
    }

    @Override
    public UInteger value1() {
        return getTagId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getAccountId();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value5() {
        return getUpdatedAt();
    }

    @Override
    public TagRecord value1(UInteger value) {
        setTagId(value);
        return this;
    }

    @Override
    public TagRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public TagRecord value3(String value) {
        setAccountId(value);
        return this;
    }

    @Override
    public TagRecord value4(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public TagRecord value5(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public TagRecord values(UInteger value1, String value2, String value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TagRecord
     */
    public TagRecord() {
        super(Tag.TAG);
    }

    /**
     * Create a detached, initialised TagRecord
     */
    public TagRecord(UInteger tagId, String name, String accountId, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Tag.TAG);

        set(0, tagId);
        set(1, name);
        set(2, accountId);
        set(3, createdAt);
        set(4, updatedAt);
    }
}
