/*
 * This file is generated by jOOQ.
 */
package habanero.extensions.database;


import habanero.extensions.database.tables.Notebook;
import habanero.extensions.database.tables.Page;
import habanero.extensions.database.tables.Section;
import habanero.extensions.database.tables.SectionTag;
import habanero.extensions.database.tables.Tag;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApiNotebook extends SchemaImpl {

    private static final long serialVersionUID = -882288100;

    /**
     * The reference instance of <code>api-notebook</code>
     */
    public static final ApiNotebook API_NOTEBOOK = new ApiNotebook();

    /**
     * The table <code>api-notebook.notebook</code>.
     */
    public final Notebook NOTEBOOK = Notebook.NOTEBOOK;

    /**
     * The table <code>api-notebook.page</code>.
     */
    public final Page PAGE = Page.PAGE;

    /**
     * The table <code>api-notebook.section</code>.
     */
    public final Section SECTION = Section.SECTION;

    /**
     * The table <code>api-notebook.section_tag</code>.
     */
    public final SectionTag SECTION_TAG = SectionTag.SECTION_TAG;

    /**
     * The table <code>api-notebook.tag</code>.
     */
    public final Tag TAG = Tag.TAG;

    /**
     * No further instances allowed
     */
    private ApiNotebook() {
        super("api-notebook", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Notebook.NOTEBOOK,
            Page.PAGE,
            Section.SECTION,
            SectionTag.SECTION_TAG,
            Tag.TAG);
    }
}
