/*
 * This file is generated by jOOQ.
 */
package habanero.extensions.database;


import habanero.extensions.database.tables.Notebook;
import habanero.extensions.database.tables.Page;
import habanero.extensions.database.tables.Section;
import habanero.extensions.database.tables.SectionTag;
import habanero.extensions.database.tables.Tag;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>api-notebook</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index NOTEBOOK_TITLE = Indexes0.NOTEBOOK_TITLE;
    public static final Index PAGE_NOTEBOOK_ID_IDX = Indexes0.PAGE_NOTEBOOK_ID_IDX;
    public static final Index PAGE_TITLE = Indexes0.PAGE_TITLE;
    public static final Index SECTION_CONTENT = Indexes0.SECTION_CONTENT;
    public static final Index SECTION_PAGE_ID_IDX = Indexes0.SECTION_PAGE_ID_IDX;
    public static final Index SECTION_TAG_FK_TAG_ID_IDX = Indexes0.SECTION_TAG_FK_TAG_ID_IDX;
    public static final Index TAG_NAME = Indexes0.TAG_NAME;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index NOTEBOOK_TITLE = Internal.createIndex("title", Notebook.NOTEBOOK, new OrderField[] { Notebook.NOTEBOOK.TITLE }, false);
        public static Index PAGE_NOTEBOOK_ID_IDX = Internal.createIndex("notebook_id_idx", Page.PAGE, new OrderField[] { Page.PAGE.NOTEBOOK_ID }, false);
        public static Index PAGE_TITLE = Internal.createIndex("title", Page.PAGE, new OrderField[] { Page.PAGE.TITLE }, false);
        public static Index SECTION_CONTENT = Internal.createIndex("content", Section.SECTION, new OrderField[] { Section.SECTION.CONTENT }, false);
        public static Index SECTION_PAGE_ID_IDX = Internal.createIndex("page_id_idx", Section.SECTION, new OrderField[] { Section.SECTION.PAGE_ID }, false);
        public static Index SECTION_TAG_FK_TAG_ID_IDX = Internal.createIndex("fk_tag_id_idx", SectionTag.SECTION_TAG, new OrderField[] { SectionTag.SECTION_TAG.TAG_ID }, false);
        public static Index TAG_NAME = Internal.createIndex("name", Tag.TAG, new OrderField[] { Tag.TAG.NAME }, false);
    }
}
