/*
 * This file is generated by jOOQ.
 */
package habanero.extensions.database;


import habanero.extensions.database.tables.Notebook;
import habanero.extensions.database.tables.Page;
import habanero.extensions.database.tables.Section;
import habanero.extensions.database.tables.SectionTag;
import habanero.extensions.database.tables.Tag;
import habanero.extensions.database.tables.records.NotebookRecord;
import habanero.extensions.database.tables.records.PageRecord;
import habanero.extensions.database.tables.records.SectionRecord;
import habanero.extensions.database.tables.records.SectionTagRecord;
import habanero.extensions.database.tables.records.TagRecord;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.jooq.types.UInteger;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>api-notebook</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<NotebookRecord, UInteger> IDENTITY_NOTEBOOK = Identities0.IDENTITY_NOTEBOOK;
    public static final Identity<PageRecord, UInteger> IDENTITY_PAGE = Identities0.IDENTITY_PAGE;
    public static final Identity<SectionRecord, UInteger> IDENTITY_SECTION = Identities0.IDENTITY_SECTION;
    public static final Identity<TagRecord, UInteger> IDENTITY_TAG = Identities0.IDENTITY_TAG;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<NotebookRecord> KEY_NOTEBOOK_PRIMARY = UniqueKeys0.KEY_NOTEBOOK_PRIMARY;
    public static final UniqueKey<NotebookRecord> KEY_NOTEBOOK_ACCOUNT_ID_ORDER_UNIQUE = UniqueKeys0.KEY_NOTEBOOK_ACCOUNT_ID_ORDER_UNIQUE;
    public static final UniqueKey<NotebookRecord> KEY_NOTEBOOK_ACCOUNT_ID_TITLE_UNIQUE = UniqueKeys0.KEY_NOTEBOOK_ACCOUNT_ID_TITLE_UNIQUE;
    public static final UniqueKey<PageRecord> KEY_PAGE_PRIMARY = UniqueKeys0.KEY_PAGE_PRIMARY;
    public static final UniqueKey<PageRecord> KEY_PAGE_NOTEBOOK_ID_ORDER_UNIQUE = UniqueKeys0.KEY_PAGE_NOTEBOOK_ID_ORDER_UNIQUE;
    public static final UniqueKey<SectionRecord> KEY_SECTION_PRIMARY = UniqueKeys0.KEY_SECTION_PRIMARY;
    public static final UniqueKey<SectionTagRecord> KEY_SECTION_TAG_PRIMARY = UniqueKeys0.KEY_SECTION_TAG_PRIMARY;
    public static final UniqueKey<TagRecord> KEY_TAG_PRIMARY = UniqueKeys0.KEY_TAG_PRIMARY;
    public static final UniqueKey<TagRecord> KEY_TAG_NAME_ACCOUNT_ID_UNIQUE = UniqueKeys0.KEY_TAG_NAME_ACCOUNT_ID_UNIQUE;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<PageRecord, NotebookRecord> FK_NOTEBOOK_ID = ForeignKeys0.FK_NOTEBOOK_ID;
    public static final ForeignKey<SectionRecord, PageRecord> FK_PAGE_ID = ForeignKeys0.FK_PAGE_ID;
    public static final ForeignKey<SectionTagRecord, SectionRecord> FK_SECTION_ID = ForeignKeys0.FK_SECTION_ID;
    public static final ForeignKey<SectionTagRecord, TagRecord> FK_TAG_ID = ForeignKeys0.FK_TAG_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<NotebookRecord, UInteger> IDENTITY_NOTEBOOK = Internal.createIdentity(Notebook.NOTEBOOK, Notebook.NOTEBOOK.NOTEBOOK_ID);
        public static Identity<PageRecord, UInteger> IDENTITY_PAGE = Internal.createIdentity(Page.PAGE, Page.PAGE.PAGE_ID);
        public static Identity<SectionRecord, UInteger> IDENTITY_SECTION = Internal.createIdentity(Section.SECTION, Section.SECTION.SECTION_ID);
        public static Identity<TagRecord, UInteger> IDENTITY_TAG = Internal.createIdentity(Tag.TAG, Tag.TAG.TAG_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<NotebookRecord> KEY_NOTEBOOK_PRIMARY = Internal.createUniqueKey(Notebook.NOTEBOOK, "KEY_notebook_PRIMARY", new TableField[] { Notebook.NOTEBOOK.NOTEBOOK_ID }, true);
        public static final UniqueKey<NotebookRecord> KEY_NOTEBOOK_ACCOUNT_ID_ORDER_UNIQUE = Internal.createUniqueKey(Notebook.NOTEBOOK, "KEY_notebook_account_id_order_unique", new TableField[] { Notebook.NOTEBOOK.ACCOUNT_ID, Notebook.NOTEBOOK.ORDER }, true);
        public static final UniqueKey<NotebookRecord> KEY_NOTEBOOK_ACCOUNT_ID_TITLE_UNIQUE = Internal.createUniqueKey(Notebook.NOTEBOOK, "KEY_notebook_account_id_title_unique", new TableField[] { Notebook.NOTEBOOK.ACCOUNT_ID, Notebook.NOTEBOOK.TITLE }, true);
        public static final UniqueKey<PageRecord> KEY_PAGE_PRIMARY = Internal.createUniqueKey(Page.PAGE, "KEY_page_PRIMARY", new TableField[] { Page.PAGE.PAGE_ID }, true);
        public static final UniqueKey<PageRecord> KEY_PAGE_NOTEBOOK_ID_ORDER_UNIQUE = Internal.createUniqueKey(Page.PAGE, "KEY_page_notebook_id_order_unique", new TableField[] { Page.PAGE.NOTEBOOK_ID, Page.PAGE.ORDER }, true);
        public static final UniqueKey<SectionRecord> KEY_SECTION_PRIMARY = Internal.createUniqueKey(Section.SECTION, "KEY_section_PRIMARY", new TableField[] { Section.SECTION.SECTION_ID }, true);
        public static final UniqueKey<SectionTagRecord> KEY_SECTION_TAG_PRIMARY = Internal.createUniqueKey(SectionTag.SECTION_TAG, "KEY_section_tag_PRIMARY", new TableField[] { SectionTag.SECTION_TAG.SECTION_ID, SectionTag.SECTION_TAG.TAG_ID }, true);
        public static final UniqueKey<TagRecord> KEY_TAG_PRIMARY = Internal.createUniqueKey(Tag.TAG, "KEY_tag_PRIMARY", new TableField[] { Tag.TAG.TAG_ID }, true);
        public static final UniqueKey<TagRecord> KEY_TAG_NAME_ACCOUNT_ID_UNIQUE = Internal.createUniqueKey(Tag.TAG, "KEY_tag_name_account_id_unique", new TableField[] { Tag.TAG.ACCOUNT_ID, Tag.TAG.NAME }, true);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<PageRecord, NotebookRecord> FK_NOTEBOOK_ID = Internal.createForeignKey(Keys.KEY_NOTEBOOK_PRIMARY, Page.PAGE, "fk_notebook_id", new TableField[] { Page.PAGE.NOTEBOOK_ID }, true);
        public static final ForeignKey<SectionRecord, PageRecord> FK_PAGE_ID = Internal.createForeignKey(Keys.KEY_PAGE_PRIMARY, Section.SECTION, "fk_page_id", new TableField[] { Section.SECTION.PAGE_ID }, true);
        public static final ForeignKey<SectionTagRecord, SectionRecord> FK_SECTION_ID = Internal.createForeignKey(Keys.KEY_SECTION_PRIMARY, SectionTag.SECTION_TAG, "fk_section_id", new TableField[] { SectionTag.SECTION_TAG.SECTION_ID }, true);
        public static final ForeignKey<SectionTagRecord, TagRecord> FK_TAG_ID = Internal.createForeignKey(Keys.KEY_TAG_PRIMARY, SectionTag.SECTION_TAG, "fk_tag_id", new TableField[] { SectionTag.SECTION_TAG.TAG_ID }, true);
    }
}
