/*
 * This file is generated by jOOQ.
 */
package habanero.extensions.database;


import habanero.extensions.database.tables.Notebook;
import habanero.extensions.database.tables.Page;
import habanero.extensions.database.tables.Section;
import habanero.extensions.database.tables.SectionTag;
import habanero.extensions.database.tables.Tag;


/**
 * Convenience access to all tables in api-notebook
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>api-notebook.notebook</code>.
     */
    public static final Notebook NOTEBOOK = Notebook.NOTEBOOK;

    /**
     * The table <code>api-notebook.page</code>.
     */
    public static final Page PAGE = Page.PAGE;

    /**
     * The table <code>api-notebook.section</code>.
     */
    public static final Section SECTION = Section.SECTION;

    /**
     * The table <code>api-notebook.section_tag</code>.
     */
    public static final SectionTag SECTION_TAG = SectionTag.SECTION_TAG;

    /**
     * The table <code>api-notebook.tag</code>.
     */
    public static final Tag TAG = Tag.TAG;
}
