/*
 * This file is generated by jOOQ.
 */
package habanero.extensions.database.tables;


import habanero.extensions.database.ApiNotebook;
import habanero.extensions.database.Indexes;
import habanero.extensions.database.Keys;
import habanero.extensions.database.tables.records.NotebookRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Notebook extends TableImpl<NotebookRecord> {

    private static final long serialVersionUID = -2138261320;

    /**
     * The reference instance of <code>api-notebook.notebook</code>
     */
    public static final Notebook NOTEBOOK = new Notebook();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NotebookRecord> getRecordType() {
        return NotebookRecord.class;
    }

    /**
     * The column <code>api-notebook.notebook.notebook_id</code>.
     */
    public final TableField<NotebookRecord, UInteger> NOTEBOOK_ID = createField(DSL.name("notebook_id"), org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>api-notebook.notebook.account_id</code>.
     */
    public final TableField<NotebookRecord, String> ACCOUNT_ID = createField(DSL.name("account_id"), org.jooq.impl.SQLDataType.CHAR(16).nullable(false), this, "");

    /**
     * The column <code>api-notebook.notebook.title</code>.
     */
    public final TableField<NotebookRecord, String> TITLE = createField(DSL.name("title"), org.jooq.impl.SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>api-notebook.notebook.order</code>.
     */
    public final TableField<NotebookRecord, UInteger> ORDER = createField(DSL.name("order"), org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>api-notebook.notebook.created_at</code>.
     */
    public final TableField<NotebookRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>api-notebook.notebook.updated_at</code>.
     */
    public final TableField<NotebookRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * Create a <code>api-notebook.notebook</code> table reference
     */
    public Notebook() {
        this(DSL.name("notebook"), null);
    }

    /**
     * Create an aliased <code>api-notebook.notebook</code> table reference
     */
    public Notebook(String alias) {
        this(DSL.name(alias), NOTEBOOK);
    }

    /**
     * Create an aliased <code>api-notebook.notebook</code> table reference
     */
    public Notebook(Name alias) {
        this(alias, NOTEBOOK);
    }

    private Notebook(Name alias, Table<NotebookRecord> aliased) {
        this(alias, aliased, null);
    }

    private Notebook(Name alias, Table<NotebookRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Notebook(Table<O> child, ForeignKey<O, NotebookRecord> key) {
        super(child, key, NOTEBOOK);
    }

    @Override
    public Schema getSchema() {
        return ApiNotebook.API_NOTEBOOK;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.NOTEBOOK_TITLE);
    }

    @Override
    public Identity<NotebookRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_NOTEBOOK;
    }

    @Override
    public UniqueKey<NotebookRecord> getPrimaryKey() {
        return Keys.KEY_NOTEBOOK_PRIMARY;
    }

    @Override
    public List<UniqueKey<NotebookRecord>> getKeys() {
        return Arrays.<UniqueKey<NotebookRecord>>asList(Keys.KEY_NOTEBOOK_PRIMARY, Keys.KEY_NOTEBOOK_ACCOUNT_ID_ORDER_UNIQUE, Keys.KEY_NOTEBOOK_ACCOUNT_ID_TITLE_UNIQUE);
    }

    @Override
    public Notebook as(String alias) {
        return new Notebook(DSL.name(alias), this);
    }

    @Override
    public Notebook as(Name alias) {
        return new Notebook(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Notebook rename(String name) {
        return new Notebook(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Notebook rename(Name name) {
        return new Notebook(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<UInteger, String, String, UInteger, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
