/*
 * This file is generated by jOOQ.
 */
package habanero.extensions.database.tables;


import habanero.extensions.database.ApiNotebook;
import habanero.extensions.database.Indexes;
import habanero.extensions.database.Keys;
import habanero.extensions.database.tables.records.PageRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Page extends TableImpl<PageRecord> {

    private static final long serialVersionUID = 958009877;

    /**
     * The reference instance of <code>api-notebook.page</code>
     */
    public static final Page PAGE = new Page();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PageRecord> getRecordType() {
        return PageRecord.class;
    }

    /**
     * The column <code>api-notebook.page.page_id</code>.
     */
    public final TableField<PageRecord, UInteger> PAGE_ID = createField(DSL.name("page_id"), org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>api-notebook.page.notebook_id</code>.
     */
    public final TableField<PageRecord, UInteger> NOTEBOOK_ID = createField(DSL.name("notebook_id"), org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>api-notebook.page.title</code>.
     */
    public final TableField<PageRecord, String> TITLE = createField(DSL.name("title"), org.jooq.impl.SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>api-notebook.page.order</code>.
     */
    public final TableField<PageRecord, UInteger> ORDER = createField(DSL.name("order"), org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>api-notebook.page.created_at</code>.
     */
    public final TableField<PageRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>api-notebook.page.updated_at</code>.
     */
    public final TableField<PageRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * Create a <code>api-notebook.page</code> table reference
     */
    public Page() {
        this(DSL.name("page"), null);
    }

    /**
     * Create an aliased <code>api-notebook.page</code> table reference
     */
    public Page(String alias) {
        this(DSL.name(alias), PAGE);
    }

    /**
     * Create an aliased <code>api-notebook.page</code> table reference
     */
    public Page(Name alias) {
        this(alias, PAGE);
    }

    private Page(Name alias, Table<PageRecord> aliased) {
        this(alias, aliased, null);
    }

    private Page(Name alias, Table<PageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Page(Table<O> child, ForeignKey<O, PageRecord> key) {
        super(child, key, PAGE);
    }

    @Override
    public Schema getSchema() {
        return ApiNotebook.API_NOTEBOOK;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PAGE_NOTEBOOK_ID_IDX, Indexes.PAGE_TITLE);
    }

    @Override
    public Identity<PageRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_PAGE;
    }

    @Override
    public UniqueKey<PageRecord> getPrimaryKey() {
        return Keys.KEY_PAGE_PRIMARY;
    }

    @Override
    public List<UniqueKey<PageRecord>> getKeys() {
        return Arrays.<UniqueKey<PageRecord>>asList(Keys.KEY_PAGE_PRIMARY, Keys.KEY_PAGE_NOTEBOOK_ID_ORDER_UNIQUE);
    }

    @Override
    public List<ForeignKey<PageRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PageRecord, ?>>asList(Keys.FK_NOTEBOOK_ID);
    }

    public Notebook notebook() {
        return new Notebook(this, Keys.FK_NOTEBOOK_ID);
    }

    @Override
    public Page as(String alias) {
        return new Page(DSL.name(alias), this);
    }

    @Override
    public Page as(Name alias) {
        return new Page(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Page rename(String name) {
        return new Page(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Page rename(Name name) {
        return new Page(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<UInteger, UInteger, String, UInteger, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
