/*
 * This file is generated by jOOQ.
 */
package habanero.extensions.database.tables;


import habanero.extensions.database.ApiNotebook;
import habanero.extensions.database.Indexes;
import habanero.extensions.database.Keys;
import habanero.extensions.database.tables.records.SectionRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Section extends TableImpl<SectionRecord> {

    private static final long serialVersionUID = -2080516662;

    /**
     * The reference instance of <code>api-notebook.section</code>
     */
    public static final Section SECTION = new Section();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SectionRecord> getRecordType() {
        return SectionRecord.class;
    }

    /**
     * The column <code>api-notebook.section.section_id</code>.
     */
    public final TableField<SectionRecord, UInteger> SECTION_ID = createField(DSL.name("section_id"), org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>api-notebook.section.page_id</code>.
     */
    public final TableField<SectionRecord, UInteger> PAGE_ID = createField(DSL.name("page_id"), org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this, "");

    /**
     * The column <code>api-notebook.section.content</code>.
     */
    public final TableField<SectionRecord, String> CONTENT = createField(DSL.name("content"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>api-notebook.section.is_trashed</code>.
     */
    public final TableField<SectionRecord, Byte> IS_TRASHED = createField(DSL.name("is_trashed"), org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>api-notebook.section.created_at</code>.
     */
    public final TableField<SectionRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>api-notebook.section.updated_at</code>.
     */
    public final TableField<SectionRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * Create a <code>api-notebook.section</code> table reference
     */
    public Section() {
        this(DSL.name("section"), null);
    }

    /**
     * Create an aliased <code>api-notebook.section</code> table reference
     */
    public Section(String alias) {
        this(DSL.name(alias), SECTION);
    }

    /**
     * Create an aliased <code>api-notebook.section</code> table reference
     */
    public Section(Name alias) {
        this(alias, SECTION);
    }

    private Section(Name alias, Table<SectionRecord> aliased) {
        this(alias, aliased, null);
    }

    private Section(Name alias, Table<SectionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Section(Table<O> child, ForeignKey<O, SectionRecord> key) {
        super(child, key, SECTION);
    }

    @Override
    public Schema getSchema() {
        return ApiNotebook.API_NOTEBOOK;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SECTION_CONTENT, Indexes.SECTION_PAGE_ID_IDX);
    }

    @Override
    public Identity<SectionRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_SECTION;
    }

    @Override
    public UniqueKey<SectionRecord> getPrimaryKey() {
        return Keys.KEY_SECTION_PRIMARY;
    }

    @Override
    public List<UniqueKey<SectionRecord>> getKeys() {
        return Arrays.<UniqueKey<SectionRecord>>asList(Keys.KEY_SECTION_PRIMARY);
    }

    @Override
    public List<ForeignKey<SectionRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SectionRecord, ?>>asList(Keys.FK_PAGE_ID);
    }

    public Page page() {
        return new Page(this, Keys.FK_PAGE_ID);
    }

    @Override
    public Section as(String alias) {
        return new Section(DSL.name(alias), this);
    }

    @Override
    public Section as(Name alias) {
        return new Section(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Section rename(String name) {
        return new Section(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Section rename(Name name) {
        return new Section(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<UInteger, UInteger, String, Byte, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
