/*
 * This file is generated by jOOQ.
 */
package habanero.extensions.database.tables;


import habanero.extensions.database.ApiNotebook;
import habanero.extensions.database.Indexes;
import habanero.extensions.database.Keys;
import habanero.extensions.database.tables.records.SectionTagRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SectionTag extends TableImpl<SectionTagRecord> {

    private static final long serialVersionUID = -1123185209;

    /**
     * The reference instance of <code>api-notebook.section_tag</code>
     */
    public static final SectionTag SECTION_TAG = new SectionTag();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SectionTagRecord> getRecordType() {
        return SectionTagRecord.class;
    }

    /**
     * The column <code>api-notebook.section_tag.section_id</code>.
     */
    public final TableField<SectionTagRecord, UInteger> SECTION_ID = createField(DSL.name("section_id"), org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>api-notebook.section_tag.tag_id</code>.
     */
    public final TableField<SectionTagRecord, UInteger> TAG_ID = createField(DSL.name("tag_id"), org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>api-notebook.section_tag.created_at</code>.
     */
    public final TableField<SectionTagRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>api-notebook.section_tag.updated_at</code>.
     */
    public final TableField<SectionTagRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * Create a <code>api-notebook.section_tag</code> table reference
     */
    public SectionTag() {
        this(DSL.name("section_tag"), null);
    }

    /**
     * Create an aliased <code>api-notebook.section_tag</code> table reference
     */
    public SectionTag(String alias) {
        this(DSL.name(alias), SECTION_TAG);
    }

    /**
     * Create an aliased <code>api-notebook.section_tag</code> table reference
     */
    public SectionTag(Name alias) {
        this(alias, SECTION_TAG);
    }

    private SectionTag(Name alias, Table<SectionTagRecord> aliased) {
        this(alias, aliased, null);
    }

    private SectionTag(Name alias, Table<SectionTagRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> SectionTag(Table<O> child, ForeignKey<O, SectionTagRecord> key) {
        super(child, key, SECTION_TAG);
    }

    @Override
    public Schema getSchema() {
        return ApiNotebook.API_NOTEBOOK;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SECTION_TAG_FK_TAG_ID_IDX);
    }

    @Override
    public UniqueKey<SectionTagRecord> getPrimaryKey() {
        return Keys.KEY_SECTION_TAG_PRIMARY;
    }

    @Override
    public List<UniqueKey<SectionTagRecord>> getKeys() {
        return Arrays.<UniqueKey<SectionTagRecord>>asList(Keys.KEY_SECTION_TAG_PRIMARY);
    }

    @Override
    public List<ForeignKey<SectionTagRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SectionTagRecord, ?>>asList(Keys.FK_SECTION_ID, Keys.FK_TAG_ID);
    }

    public Section section() {
        return new Section(this, Keys.FK_SECTION_ID);
    }

    public Tag tag() {
        return new Tag(this, Keys.FK_TAG_ID);
    }

    @Override
    public SectionTag as(String alias) {
        return new SectionTag(DSL.name(alias), this);
    }

    @Override
    public SectionTag as(Name alias) {
        return new SectionTag(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SectionTag rename(String name) {
        return new SectionTag(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SectionTag rename(Name name) {
        return new SectionTag(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<UInteger, UInteger, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
